services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ${MARIADB_FILES}:/var/lib/mysql

  tomcat:
    image: tomcat:10.1
    container_name: tomcat
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ${TOMCAT_WEBAPPS}:/usr/local/tomcat/webapps
    depends_on:
      - mariadb

volumes:
  mariadb_data:
